# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  command = "vue-cli-service build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    # X-XSS-Protection = "1; mode=block"