# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  command = "vue-cli-service build"
  publish = "dist"

[[redirects]]
  from = "https://cesc12-reg.netlify.com/*"
  to = "https://reg.cesc.kmi.tl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    # X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src https:; report-uri https://sentry.io/api/1400948/security/?sentry_key=7ea9755df0ec49369a817c19345331fe"
    Expect-CT = "max-age=86400, report-uri=\"https://sentry.io/api/1400948/security/?sentry_key=7ea9755df0ec49369a817c19345331fe\""
